// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: enclave/apps/confidential-http/types/types.proto

package types

import (
	frameworktypes "github.com/smartcontractkit/chainlink-confidential-compute/types/frameworktypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HeaderValues represents multiple values for a single header key.
type HeaderValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeaderValues) Reset() {
	*x = HeaderValues{}
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeaderValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeaderValues) ProtoMessage() {}

func (x *HeaderValues) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeaderValues.ProtoReflect.Descriptor instead.
func (*HeaderValues) Descriptor() ([]byte, []int) {
	return file_enclave_apps_confidential_http_types_types_proto_rawDescGZIP(), []int{0}
}

func (x *HeaderValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Request contains the specific HTTP fields used to make an HTTP request from the enclave.
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// URL is the endpoint to which the request is sent.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Method is the HTTP method used to make the request (GET, POST, PUT, DELETE, etc.).
	Method string `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	// Body is the request body - either a string template or raw bytes.
	//
	// Types that are valid to be assigned to Body:
	//
	//	*Request_BodyString
	//	*Request_BodyBytes
	Body isRequest_Body `protobuf_oneof:"body"`
	// multi_headers are the request headers as name-value pairs.
	// Supports multiple values per header key.
	MultiHeaders map[string]*HeaderValues `protobuf:"bytes,4,rep,name=multi_headers,json=multiHeaders,proto3" json:"multi_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// TemplatePublicValues are the public values that will be used to fill in the request body and header templates.
	// It is a mapping of the template variable names to their values.
	TemplatePublicValues map[string]string `protobuf:"bytes,5,rep,name=template_public_values,json=templatePublicValues,proto3" json:"template_public_values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// CustomRootCaCertPEM is an optional field that allows the user to specify a custom root CA certificate
	// (in PEM Format) for the request. The enclave will use this root CA certificate to verify the external
	// server's TLS certificate.
	CustomRootCaCertPem []byte `protobuf:"bytes,6,opt,name=custom_root_ca_cert_pem,json=customRootCaCertPem,proto3" json:"custom_root_ca_cert_pem,omitempty"`
	// Timeout is the request timeout duration.
	Timeout *durationpb.Duration `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// encrypt_output controls whether the enclave response should be encrypted.
	// If true, the response will be AES-GCM encrypted using the
	// "san_marino_aes_gcm_encryption_key" secret.
	// Default is false (response returned unencrypted).
	EncryptOutput bool `protobuf:"varint,9,opt,name=encrypt_output,json=encryptOutput,proto3" json:"encrypt_output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_enclave_apps_confidential_http_types_types_proto_rawDescGZIP(), []int{1}
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetBody() isRequest_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Request) GetBodyString() string {
	if x != nil {
		if x, ok := x.Body.(*Request_BodyString); ok {
			return x.BodyString
		}
	}
	return ""
}

func (x *Request) GetBodyBytes() []byte {
	if x != nil {
		if x, ok := x.Body.(*Request_BodyBytes); ok {
			return x.BodyBytes
		}
	}
	return nil
}

func (x *Request) GetMultiHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.MultiHeaders
	}
	return nil
}

func (x *Request) GetTemplatePublicValues() map[string]string {
	if x != nil {
		return x.TemplatePublicValues
	}
	return nil
}

func (x *Request) GetCustomRootCaCertPem() []byte {
	if x != nil {
		return x.CustomRootCaCertPem
	}
	return nil
}

func (x *Request) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *Request) GetEncryptOutput() bool {
	if x != nil {
		return x.EncryptOutput
	}
	return false
}

type isRequest_Body interface {
	isRequest_Body()
}

type Request_BodyString struct {
	BodyString string `protobuf:"bytes,3,opt,name=body_string,json=bodyString,proto3,oneof"`
}

type Request_BodyBytes struct {
	BodyBytes []byte `protobuf:"bytes,8,opt,name=body_bytes,json=bodyBytes,proto3,oneof"`
}

func (*Request_BodyString) isRequest_Body() {}

func (*Request_BodyBytes) isRequest_Body() {}

// ConfidentialHTTPRequest is the input type users provide.
type ConfidentialHTTPRequest struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	VaultDonSecrets []*frameworktypes.SecretIdentifier `protobuf:"bytes,1,rep,name=vault_don_secrets,json=vaultDonSecrets,proto3" json:"vault_don_secrets,omitempty"`
	Request         *Request                           `protobuf:"bytes,2,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ConfidentialHTTPRequest) Reset() {
	*x = ConfidentialHTTPRequest{}
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfidentialHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfidentialHTTPRequest) ProtoMessage() {}

func (x *ConfidentialHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfidentialHTTPRequest.ProtoReflect.Descriptor instead.
func (*ConfidentialHTTPRequest) Descriptor() ([]byte, []int) {
	return file_enclave_apps_confidential_http_types_types_proto_rawDescGZIP(), []int{2}
}

func (x *ConfidentialHTTPRequest) GetVaultDonSecrets() []*frameworktypes.SecretIdentifier {
	if x != nil {
		return x.VaultDonSecrets
	}
	return nil
}

func (x *ConfidentialHTTPRequest) GetRequest() *Request {
	if x != nil {
		return x.Request
	}
	return nil
}

// Response is what the user receives.
type Response struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	StatusCode uint32                 `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body       []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	// multi_headers are the response headers.
	// Supports multiple values per header key.
	MultiHeaders  map[string]*HeaderValues `protobuf:"bytes,3,rep,name=multi_headers,json=multiHeaders,proto3" json:"multi_headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_enclave_apps_confidential_http_types_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_enclave_apps_confidential_http_types_types_proto_rawDescGZIP(), []int{3}
}

func (x *Response) GetStatusCode() uint32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *Response) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Response) GetMultiHeaders() map[string]*HeaderValues {
	if x != nil {
		return x.MultiHeaders
	}
	return nil
}

var File_enclave_apps_confidential_http_types_types_proto protoreflect.FileDescriptor

const file_enclave_apps_confidential_http_types_types_proto_rawDesc = "" +
	"\n" +
	"0enclave/apps/confidential-http/types/types.proto\x12\x05types\x1a$types/frameworktypes/framework.proto\x1a\x1egoogle/protobuf/duration.proto\"&\n" +
	"\fHeaderValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\xd7\x04\n" +
	"\aRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12!\n" +
	"\vbody_string\x18\x03 \x01(\tH\x00R\n" +
	"bodyString\x12\x1f\n" +
	"\n" +
	"body_bytes\x18\b \x01(\fH\x00R\tbodyBytes\x12E\n" +
	"\rmulti_headers\x18\x04 \x03(\v2 .types.Request.MultiHeadersEntryR\fmultiHeaders\x12^\n" +
	"\x16template_public_values\x18\x05 \x03(\v2(.types.Request.TemplatePublicValuesEntryR\x14templatePublicValues\x124\n" +
	"\x17custom_root_ca_cert_pem\x18\x06 \x01(\fR\x13customRootCaCertPem\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12%\n" +
	"\x0eencrypt_output\x18\t \x01(\bR\rencryptOutput\x1aT\n" +
	"\x11MultiHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.types.HeaderValuesR\x05value:\x028\x01\x1aG\n" +
	"\x19TemplatePublicValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x06\n" +
	"\x04body\"\x91\x01\n" +
	"\x17ConfidentialHTTPRequest\x12L\n" +
	"\x11vault_don_secrets\x18\x01 \x03(\v2 .frameworktypes.SecretIdentifierR\x0fvaultDonSecrets\x12(\n" +
	"\arequest\x18\x02 \x01(\v2\x0e.types.RequestR\arequest\"\xdd\x01\n" +
	"\bResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\rR\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12F\n" +
	"\rmulti_headers\x18\x03 \x03(\v2!.types.Response.MultiHeadersEntryR\fmultiHeaders\x1aT\n" +
	"\x11MultiHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.types.HeaderValuesR\x05value:\x028\x01BaZ_github.com/smartcontractkit/chainlink-confidential-compute/enclave/apps/confidential-http/typesb\x06proto3"

var (
	file_enclave_apps_confidential_http_types_types_proto_rawDescOnce sync.Once
	file_enclave_apps_confidential_http_types_types_proto_rawDescData []byte
)

func file_enclave_apps_confidential_http_types_types_proto_rawDescGZIP() []byte {
	file_enclave_apps_confidential_http_types_types_proto_rawDescOnce.Do(func() {
		file_enclave_apps_confidential_http_types_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enclave_apps_confidential_http_types_types_proto_rawDesc), len(file_enclave_apps_confidential_http_types_types_proto_rawDesc)))
	})
	return file_enclave_apps_confidential_http_types_types_proto_rawDescData
}

var file_enclave_apps_confidential_http_types_types_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_enclave_apps_confidential_http_types_types_proto_goTypes = []any{
	(*HeaderValues)(nil),                    // 0: types.HeaderValues
	(*Request)(nil),                         // 1: types.Request
	(*ConfidentialHTTPRequest)(nil),         // 2: types.ConfidentialHTTPRequest
	(*Response)(nil),                        // 3: types.Response
	nil,                                     // 4: types.Request.MultiHeadersEntry
	nil,                                     // 5: types.Request.TemplatePublicValuesEntry
	nil,                                     // 6: types.Response.MultiHeadersEntry
	(*durationpb.Duration)(nil),             // 7: google.protobuf.Duration
	(*frameworktypes.SecretIdentifier)(nil), // 8: frameworktypes.SecretIdentifier
}
var file_enclave_apps_confidential_http_types_types_proto_depIdxs = []int32{
	4, // 0: types.Request.multi_headers:type_name -> types.Request.MultiHeadersEntry
	5, // 1: types.Request.template_public_values:type_name -> types.Request.TemplatePublicValuesEntry
	7, // 2: types.Request.timeout:type_name -> google.protobuf.Duration
	8, // 3: types.ConfidentialHTTPRequest.vault_don_secrets:type_name -> frameworktypes.SecretIdentifier
	1, // 4: types.ConfidentialHTTPRequest.request:type_name -> types.Request
	6, // 5: types.Response.multi_headers:type_name -> types.Response.MultiHeadersEntry
	0, // 6: types.Request.MultiHeadersEntry.value:type_name -> types.HeaderValues
	0, // 7: types.Response.MultiHeadersEntry.value:type_name -> types.HeaderValues
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_enclave_apps_confidential_http_types_types_proto_init() }
func file_enclave_apps_confidential_http_types_types_proto_init() {
	if File_enclave_apps_confidential_http_types_types_proto != nil {
		return
	}
	file_enclave_apps_confidential_http_types_types_proto_msgTypes[1].OneofWrappers = []any{
		(*Request_BodyString)(nil),
		(*Request_BodyBytes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enclave_apps_confidential_http_types_types_proto_rawDesc), len(file_enclave_apps_confidential_http_types_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enclave_apps_confidential_http_types_types_proto_goTypes,
		DependencyIndexes: file_enclave_apps_confidential_http_types_types_proto_depIdxs,
		MessageInfos:      file_enclave_apps_confidential_http_types_types_proto_msgTypes,
	}.Build()
	File_enclave_apps_confidential_http_types_types_proto = out.File
	file_enclave_apps_confidential_http_types_types_proto_goTypes = nil
	file_enclave_apps_confidential_http_types_types_proto_depIdxs = nil
}
