// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: types/frameworktypes/framework.proto

package frameworktypes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SecretIdentifier specifies a secret that needs to be fetched from a vault.
type SecretIdentifier struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Owner         *string                `protobuf:"bytes,3,opt,name=owner,proto3,oneof" json:"owner,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SecretIdentifier) Reset() {
	*x = SecretIdentifier{}
	mi := &file_types_frameworktypes_framework_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretIdentifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretIdentifier) ProtoMessage() {}

func (x *SecretIdentifier) ProtoReflect() protoreflect.Message {
	mi := &file_types_frameworktypes_framework_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecretIdentifier.ProtoReflect.Descriptor instead.
func (*SecretIdentifier) Descriptor() ([]byte, []int) {
	return file_types_frameworktypes_framework_proto_rawDescGZIP(), []int{0}
}

func (x *SecretIdentifier) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SecretIdentifier) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SecretIdentifier) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

var File_types_frameworktypes_framework_proto protoreflect.FileDescriptor

const file_types_frameworktypes_framework_proto_rawDesc = "" +
	"\n" +
	"$types/frameworktypes/framework.proto\x12\x0eframeworktypes\"g\n" +
	"\x10SecretIdentifier\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x19\n" +
	"\x05owner\x18\x03 \x01(\tH\x00R\x05owner\x88\x01\x01B\b\n" +
	"\x06_ownerBGZEgithub.com/smartcontractkit/confidential-compute/types/frameworktypesb\x06proto3"

var (
	file_types_frameworktypes_framework_proto_rawDescOnce sync.Once
	file_types_frameworktypes_framework_proto_rawDescData []byte
)

func file_types_frameworktypes_framework_proto_rawDescGZIP() []byte {
	file_types_frameworktypes_framework_proto_rawDescOnce.Do(func() {
		file_types_frameworktypes_framework_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_types_frameworktypes_framework_proto_rawDesc), len(file_types_frameworktypes_framework_proto_rawDesc)))
	})
	return file_types_frameworktypes_framework_proto_rawDescData
}

var file_types_frameworktypes_framework_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_types_frameworktypes_framework_proto_goTypes = []any{
	(*SecretIdentifier)(nil), // 0: frameworktypes.SecretIdentifier
}
var file_types_frameworktypes_framework_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_types_frameworktypes_framework_proto_init() }
func file_types_frameworktypes_framework_proto_init() {
	if File_types_frameworktypes_framework_proto != nil {
		return
	}
	file_types_frameworktypes_framework_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_types_frameworktypes_framework_proto_rawDesc), len(file_types_frameworktypes_framework_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_frameworktypes_framework_proto_goTypes,
		DependencyIndexes: file_types_frameworktypes_framework_proto_depIdxs,
		MessageInfos:      file_types_frameworktypes_framework_proto_msgTypes,
	}.Build()
	File_types_frameworktypes_framework_proto = out.File
	file_types_frameworktypes_framework_proto_goTypes = nil
	file_types_frameworktypes_framework_proto_depIdxs = nil
}
