{
 "title": "Confidential HTTP Enclave Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Enclave CPU Utilization Ratio",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_utilization_ratio{k8s_namespace_name=\"enclave\", k8s_container_name=\"enclave\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Enclave Memory vs Limit",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k8s_container_memory_node_utilization_ratio{k8s_namespace_name=\"enclave\", k8s_container_name=\"enclave\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  {
   "title": "Enclave Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{k8s_namespace_name=\"enclave\", k8s_container_name=\"enclave\"}",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  }
 ]
}