// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.1
// source: capabilities/framework/test.proto

package framework

import (
	frameworktypes "github.com/smartcontractkit/confidential-compute/types/frameworktypes"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Test-specific input for testing the generic enclave capability
type TestInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestField     string                 `protobuf:"bytes,1,opt,name=test_field,json=testField,proto3" json:"test_field,omitempty"`
	TestArray     []string               `protobuf:"bytes,2,rep,name=test_array,json=testArray,proto3" json:"test_array,omitempty"`
	TestNumber    int32                  `protobuf:"varint,3,opt,name=test_number,json=testNumber,proto3" json:"test_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestInput) Reset() {
	*x = TestInput{}
	mi := &file_capabilities_framework_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestInput) ProtoMessage() {}

func (x *TestInput) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_framework_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestInput.ProtoReflect.Descriptor instead.
func (*TestInput) Descriptor() ([]byte, []int) {
	return file_capabilities_framework_test_proto_rawDescGZIP(), []int{0}
}

func (x *TestInput) GetTestField() string {
	if x != nil {
		return x.TestField
	}
	return ""
}

func (x *TestInput) GetTestArray() []string {
	if x != nil {
		return x.TestArray
	}
	return nil
}

func (x *TestInput) GetTestNumber() int32 {
	if x != nil {
		return x.TestNumber
	}
	return 0
}

type TestOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestOutput) Reset() {
	*x = TestOutput{}
	mi := &file_capabilities_framework_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestOutput) ProtoMessage() {}

func (x *TestOutput) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_framework_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestOutput.ProtoReflect.Descriptor instead.
func (*TestOutput) Descriptor() ([]byte, []int) {
	return file_capabilities_framework_test_proto_rawDescGZIP(), []int{1}
}

func (x *TestOutput) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *TestOutput) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type TestActionInput struct {
	state           protoimpl.MessageState             `protogen:"open.v1"`
	VaultDonSecrets []*frameworktypes.SecretIdentifier `protobuf:"bytes,1,rep,name=vault_don_secrets,json=vaultDonSecrets,proto3" json:"vault_don_secrets,omitempty"`
	Input           *TestInput                         `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TestActionInput) Reset() {
	*x = TestActionInput{}
	mi := &file_capabilities_framework_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestActionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestActionInput) ProtoMessage() {}

func (x *TestActionInput) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_framework_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestActionInput.ProtoReflect.Descriptor instead.
func (*TestActionInput) Descriptor() ([]byte, []int) {
	return file_capabilities_framework_test_proto_rawDescGZIP(), []int{2}
}

func (x *TestActionInput) GetVaultDonSecrets() []*frameworktypes.SecretIdentifier {
	if x != nil {
		return x.VaultDonSecrets
	}
	return nil
}

func (x *TestActionInput) GetInput() *TestInput {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_capabilities_framework_test_proto protoreflect.FileDescriptor

const file_capabilities_framework_test_proto_rawDesc = "" +
	"\n" +
	"!capabilities/framework/test.proto\x12\tframework\x1a$types/frameworktypes/framework.proto\"j\n" +
	"\tTestInput\x12\x1d\n" +
	"\n" +
	"test_field\x18\x01 \x01(\tR\ttestField\x12\x1d\n" +
	"\n" +
	"test_array\x18\x02 \x03(\tR\ttestArray\x12\x1f\n" +
	"\vtest_number\x18\x03 \x01(\x05R\n" +
	"testNumber\">\n" +
	"\n" +
	"TestOutput\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8b\x01\n" +
	"\x0fTestActionInput\x12L\n" +
	"\x11vault_don_secrets\x18\x01 \x03(\v2 .frameworktypes.SecretIdentifierR\x0fvaultDonSecrets\x12*\n" +
	"\x05input\x18\x02 \x01(\v2\x14.framework.TestInputR\x05inputBIZGgithub.com/smartcontractkit/confidential-compute/capabilities/frameworkb\x06proto3"

var (
	file_capabilities_framework_test_proto_rawDescOnce sync.Once
	file_capabilities_framework_test_proto_rawDescData []byte
)

func file_capabilities_framework_test_proto_rawDescGZIP() []byte {
	file_capabilities_framework_test_proto_rawDescOnce.Do(func() {
		file_capabilities_framework_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capabilities_framework_test_proto_rawDesc), len(file_capabilities_framework_test_proto_rawDesc)))
	})
	return file_capabilities_framework_test_proto_rawDescData
}

var file_capabilities_framework_test_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_capabilities_framework_test_proto_goTypes = []any{
	(*TestInput)(nil),                       // 0: framework.TestInput
	(*TestOutput)(nil),                      // 1: framework.TestOutput
	(*TestActionInput)(nil),                 // 2: framework.TestActionInput
	(*frameworktypes.SecretIdentifier)(nil), // 3: frameworktypes.SecretIdentifier
}
var file_capabilities_framework_test_proto_depIdxs = []int32{
	3, // 0: framework.TestActionInput.vault_don_secrets:type_name -> frameworktypes.SecretIdentifier
	0, // 1: framework.TestActionInput.input:type_name -> framework.TestInput
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_capabilities_framework_test_proto_init() }
func file_capabilities_framework_test_proto_init() {
	if File_capabilities_framework_test_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capabilities_framework_test_proto_rawDesc), len(file_capabilities_framework_test_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_capabilities_framework_test_proto_goTypes,
		DependencyIndexes: file_capabilities_framework_test_proto_depIdxs,
		MessageInfos:      file_capabilities_framework_test_proto_msgTypes,
	}.Build()
	File_capabilities_framework_test_proto = out.File
	file_capabilities_framework_test_proto_goTypes = nil
	file_capabilities_framework_test_proto_depIdxs = nil
}
