name: Ensure Postman Echo is Responsive

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - 'release/**'

jobs:
  check-postman-echo:
    permissions: 
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Postman Echo Health
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 https://postman-echo.com/get)
          if [ "$response" -eq 200 ]; then
            echo "✅ Postman Echo is responsive (HTTP $response)"
          else
            echo "❌ Postman Echo is not responsive (HTTP $response)"
            exit 1
          fi